package Interfaz;

import Datos.Conexion;
import Datos.Datos_Cliente;
import Datos.Datos_Comprende;
import Datos.Datos_Consultas;
import Datos.Datos_Habitacion;
import Datos.Datos_Reserva;
import Interfaz.Submenu.CalculoReserva;
import Modelo.Modelo_Cliente;
import Modelo.Modelo_Comprende;
import Modelo.Modelo_Habitacion;
import Modelo.Modelo_Reserva;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.Validador;

/**
 *
 * @author JasonllPaul
 */
public final class CheckOut extends javax.swing.JDialog {

    Modelo.Modelo_Reserva reserva;
    Modelo.Modelo_Hotel hotel;
    Modelo.Modelo_Comprende comprende;
    Datos_Habitacion habitacionControlador;
    Datos_Comprende comprendeControlador;
    Datos_Reserva reservaControlador;
    Datos_Cliente clienteControlador;
    Datos_Consultas consultasControlador;
    Conexion conexion;
    Validador validador;
    boolean calculado;
    boolean encontrado;

    /**
     * Creates new form MenuReserva
     *
     * @param parent
     * @param modal
     * @param hotel
     * @param conexion
     */
    public CheckOut(java.awt.Frame parent, boolean modal, Modelo.Modelo_Hotel hotel, Conexion conexion) {
        super(parent, modal);
        initComponents();
        this.validador = new Validador();
        this.calculado = false;
        this.encontrado = false;
        this.hotel = hotel;
        this.conexion = conexion;
        consultasControlador = new Datos_Consultas(this.conexion);
        habitacionControlador = new Datos_Habitacion(conexion);
        reservaControlador = new Datos_Reserva(conexion);
        comprendeControlador = new Datos_Comprende(conexion);
        reserva = new Modelo_Reserva();
    }

    public int buscarCliente() {
        ArrayList<String> array = new ArrayList<>();
        if (txtDni.getText().length() > 0) {
            Modelo_Cliente cliente = new Modelo_Cliente();
            try {
                cliente.setCliDni(Integer.parseInt(txtDni.getText()));
            } catch (java.lang.NumberFormatException e) {
                System.out.println("Excepción: " + e.getMessage());
            }
            clienteControlador = new Datos_Cliente(this.conexion);
            ResultSet resTodos = clienteControlador.buscarRegistroClientes(cliente);

            try {
                while (resTodos.next()) {
                    array.add(resTodos.getObject("CLIDNI").toString());
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        return array.size();
    }

    public void cargarCombo(JComboBox<String> cmb) {
        cmb.removeAllItems();
        ArrayList habitaciones = getValoresTabla("HABID");

        for (int i = 0; i < habitaciones.size(); i++) {
            cmb.addItem(habitaciones.get(i).toString());
        }
    }

    public ArrayList getValoresTabla(String nombreColumna) {
        ResultSet resTodos = habitacionControlador.consultarHabitacion("Libre", hotel.getHotId());
        ArrayList<String> array = new ArrayList<>();
        try {
            while (resTodos.next()) {
                array.add(resTodos.getObject(nombreColumna).toString());
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return array;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCalculo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblCalculo = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblEstadoDni = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        btnCancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(102, 51, 0));
        panelTitulo.setForeground(new java.awt.Color(102, 51, 0));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CHECK-OUT");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        txtDni.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniKeyReleased(evt);
            }
        });

        lblDni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDni.setText("DNI Cliente:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHECK-OUT");

        btnGuardar.setBackground(new java.awt.Color(0, 102, 204));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("+ Crear");
        btnGuardar.setFocusable(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCalculo.setEditable(false);
        txtCalculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalculo.setText("$ 0.00");
        txtCalculo.setFocusable(false);
        txtCalculo.setRequestFocusEnabled(false);

        lblCalculo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCalculo.setText("TOTAL:");

        btnCalcular.setBackground(new java.awt.Color(0, 153, 153));
        btnCalcular.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setFocusable(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblEstadoDni.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEstadoDni.setForeground(new java.awt.Color(0, 153, 51));
        lblEstadoDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Número de Reserva", "Hotel", "Fecha Inicio", "Fecha Fin", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblReserva);

        btnCancelar1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setText("Listo");
        btnCancelar1.setFocusable(false);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEscritorioLayout = new javax.swing.GroupLayout(panelEscritorio);
        panelEscritorio.setLayout(panelEscritorioLayout);
        panelEscritorioLayout.setHorizontalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscritorioLayout.createSequentialGroup()
                .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                    .addGroup(panelEscritorioLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEscritorioLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEstadoDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                            .addGroup(panelEscritorioLayout.createSequentialGroup()
                                .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelEscritorioLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(lblCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCancelar1))
                                .addGap(462, 462, 462)
                                .addComponent(btnCalcular))
                            .addGroup(panelEscritorioLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(btnCancelar)
                                .addGap(42, 42, 42)
                                .addComponent(btnGuardar))))
                    .addGroup(panelEscritorioLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEscritorioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEscritorioLayout.setVerticalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscritorioLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEscritorioLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEscritorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(lblEstadoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(lblCalculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (calculado) {
            try {
                inicialiarReserva();

                if (reservaControlador.insertarReservas(reserva) == 1) {

                } else {
                    JOptionPane.showMessageDialog(this, "Reserva no registrada, Cliente " + txtDni.getText() + " no ha sido registrado");
                }
            } catch (java.lang.NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese el DNI del cliente correctamente");
            } catch (SQLException ex) {
                Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor calcule el total");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (validar()) {

        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyReleased

        validador.validarTamanio(txtDni);

        if (buscarCliente() == 1) {
            lblEstadoDni.setForeground(new Color(0, 153, 51));
            lblEstadoDni.setText("Cliente registrado");
            encontrado = true;
        } else {
            lblEstadoDni.setForeground(Color.red);
            lblEstadoDni.setText("DNI no encontrado");
            encontrado = false;
        }

        if (!validador.validarVacio(txtDni)) {
            lblEstadoDni.setText("");
            encontrado = false;
        }

    }//GEN-LAST:event_txtDniKeyReleased

    private void txtDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (encontrado) {
                llenarTablaReserva();
            }
        }

    }//GEN-LAST:event_txtDniKeyPressed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    public void llenarTablaReserva() {
        ResultSet resTodos = consultasControlador.joinReservaHotel(Integer.parseInt(txtDni.getText()));
        try {
            tblReserva.setModel(MenuPrincipal.ConstruirModeloDeDatos(resTodos));
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void inicialiarReserva() throws SQLException {
        ResultSet res = reservaControlador.selectSequence(); // Obtiene el valor del autoincremental para la llave primaria
        ArrayList<String> array = new ArrayList<>();
        while (res.next()) {
            reserva.setResId(Integer.parseInt(res.getObject("NEXTVAL").toString()));
        }
        reserva.setCliDni(Integer.parseInt(txtDni.getText()));
        reserva.setHotId(hotel.getHotId());
        reserva.setRestotal(Float.parseFloat(txtCalculo.getText().replace("$", "")));
        reservaControlador = new Datos_Reserva(this.conexion);
    }

    public boolean validar() {
        if (validador.validarVacio(txtDni)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto DNI está vacío");
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckOut dialog = new CheckOut(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCalculo;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEstadoDni;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelEscritorio;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tblReserva;
    private javax.swing.JTextField txtCalculo;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
