/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.*;
import Interfaz.Submenu.SubMenuHotel;
import Modelo.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public final class MenuPrincipal extends javax.swing.JFrame {

    private final String NOMBRE = "CABD", CONTRASENIA = "oracle";
    Conexion conexion;
    Datos_Hotel hotelControlador;
    Datos_Reserva reservaControlador;
    Datos_Habitacion habitacionControlador;
    Modelo_Hotel hotelSeleccionado;
    Modelo_Habitacion habitacion;

    /**
     * Creates new form MenuConsulta
     */
    public MenuPrincipal() {
        initComponents();
        inicializarAtributos();
    }

    public void inicializarAtributos() {
        conexion = new Conexion(this.NOMBRE, this.CONTRASENIA);
        this.hotelControlador = new Datos_Hotel(conexion);
        this.reservaControlador = new Datos_Reserva(conexion);
        this.habitacionControlador = new Datos_Habitacion(conexion);
        llenarTablaTodosHoteles();
        llenarTablaTodasReservas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformacion = new javax.swing.JTable();
        lblBaseDatos = new javax.swing.JLabel();
        lblBaseDatosConexion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInformacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInformacion);

        escritorio.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 740, 130);

        lblBaseDatos.setText("CONECTADO A:");
        escritorio.add(lblBaseDatos);
        lblBaseDatos.setBounds(40, 290, 170, 40);
        escritorio.add(lblBaseDatosConexion);
        lblBaseDatosConexion.setBounds(40, 324, 210, 30);

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADENA HOTELERA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        escritorio.add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 100);

        btnReserva.setText("Crear Reserva");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        escritorio.add(btnReserva);
        btnReserva.setBounds(620, 280, 90, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        escritorio.add(jButton1);
        jButton1.setBounds(370, 290, 73, 23);

        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblReserva);

        escritorio.add(jScrollPane2);
        jScrollPane2.setBounds(90, 370, 452, 150);

        jMenu1.setText("Conexión");

        jMenuItem2.setText("Nueva Conexión");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Desconectar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestionar");

        jMenuItem1.setText("Hotel");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setText("Empleado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        if (conexion != null) {
            MenuHotel mh = new MenuHotel(this, true, this.conexion);
            mh.setVisible(true);
            llenarTablaTodosHoteles();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay conexión con una base de datos");
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MenuConexion mc = new MenuConexion(this, rootPaneCheckingEnabled);
        mc.setVisible(true);
        System.out.println(mc.getConexion() + " " + mc.getContrasenia());
        conexion = new Conexion(this.NOMBRE, this.CONTRASENIA);
        if (conexion != null) {
            inicializarAtributos();
            llenarTablaTodosHoteles();
            lblBaseDatosConexion.setText(hotelControlador.getConexion().getNombre());
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.conexion = null;
        lblBaseDatosConexion.setText("Desconectado");
        tblInformacion.removeAll();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        if (conexion != null) {
            MenuEmpleado me = new MenuEmpleado(this, true, this.conexion);
            me.setVisible(true);
            llenarTablaTodosHoteles();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay conexión con una base de datos");
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void tblInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInformacionMouseClicked
        try {
            if ( (evt.getButton() == 3) && (tblInformacion.getSelectedRow()!= -1) ) { // 3 es click derecho
                reservarHotel();
                SubMenuHotel sm = new SubMenuHotel(evt.getLocationOnScreen(), this.hotelSeleccionado,conexion);
                sm.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("ERROR: " + e.getMessage());
        }
    }//GEN-LAST:event_tblInformacionMouseClicked

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        try {
            reservarHotel();

            MenuReserva mr = new MenuReserva(this, true, hotelSeleccionado,this.conexion);
            mr.setVisible(true);
        } catch (NullPointerException e) {
            System.out.println("No ha seleccionado una fila de hotel");
        }
    }//GEN-LAST:event_btnReservaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    public static void registrar(Modelo modelo) {

        System.out.println(modelo.registrar());

    }

    public void reservarHotel() {
        try {
            int pos = tblInformacion.getSelectedRow(); // posición de la fila seleccionada
            int numColumnas = tblInformacion.getColumnCount(); // número de columnas del modelo

            int hotId = Integer.parseInt(tblInformacion.getValueAt(pos, 0).toString());
            int ciuId = Integer.parseInt(tblInformacion.getValueAt(pos, 1).toString());
            int empdni = Integer.parseInt(tblInformacion.getValueAt(pos, 2).toString());
            int catId = Integer.parseInt(tblInformacion.getValueAt(pos, 3).toString());
            String hotNombre = tblInformacion.getValueAt(pos, 4).toString();
            String hotDireccion = tblInformacion.getValueAt(pos, 5).toString();

            hotelSeleccionado = new Modelo_Hotel(hotId, ciuId, empdni, catId, hotNombre, hotDireccion);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("No ha seleccionado una fila de hotel");
        }
    }

    private static DefaultTableModel ConstruirModeloDeDatos(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }

    public void llenarTablaTodosHoteles() {
        ResultSet resTodos = hotelControlador.consultarTodo();
        try {
            tblInformacion.setModel(ConstruirModeloDeDatos(resTodos));
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void llenarTablaTodasReservas() {
        ResultSet resTodos = reservaControlador.consultarTodo();
        try {
            tblReserva.setModel(ConstruirModeloDeDatos(resTodos));
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserva;
    private javax.swing.JLayeredPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBaseDatos;
    private javax.swing.JLabel lblBaseDatosConexion;
    private javax.swing.JTable tblInformacion;
    private javax.swing.JTable tblReserva;
    // End of variables declaration//GEN-END:variables
}
